lib/omg_performance/runner.ex:61: Type specification 'Elixir.OMG.Performance.Runner':wait_for(registry::pid() | atom()) -> 'ok' is a supertype of the success typing: 'Elixir.OMG.Performance.Runner':wait_for(pid()) -> 'ok'
test/support/conformance/merkle_proofs.ex:43: Expression produces a value of type <<_:224>>, but this value is unmatched
test/support/conformance/merkle_proofs.ex:55: Guard test _@3::<<_:224>> =:= 'false' can never succeed
test/support/conformance/signatures_hashes.ex:49: Expression produces a value of type {'error','malformed_address' | 'malformed_inputs' | 'malformed_metadata' | 'malformed_outputs' | 'malformed_transaction' | 'malformed_transaction_rlp' | 'unrecognized_transaction_type'}, but this value is unmatched
test/support/conformance/signatures_hashes.ex:49: Guard test _@3::{'error','malformed_address' | 'malformed_inputs' | 'malformed_metadata' | 'malformed_outputs' | 'malformed_transaction' | 'malformed_transaction_rlp' | 'unrecognized_transaction_type'} =:= 'false' can never succeed
test/support/conformance/signatures_hashes.ex:54: Expression produces a value of type <<_:224>>, but this value is unmatched
test/support/conformance/signatures_hashes.ex:79: The pattern {'error', 'unrecognized_output_type'} can never match the type {'error','malformed_address' | 'malformed_inputs' | 'malformed_metadata' | 'malformed_outputs' | 'malformed_transaction' | 'malformed_transaction_rlp'}
test/support/conformance/signatures_hashes.ex:129: Guard test _@11::<<_:224>> =:= 'false' can never succeed
test/support/conformance/signatures_hashes_case.ex:40: The created fun has no local return
test/support/dev_geth.ex:55: The created fun has no local return
test/support/dev_geth.ex:62: Function stop/1 has no local return
test/support/dev_geth.ex:65: The pattern {'exit_status', 35072} can never match the type 'ok' | {'error',_}
test/support/dev_helper.ex:146: The call 'Elixir.Support.DevHelper':unlock_if_possible(_account_enc@1::any(),'geth') will never return since it differs in the 2nd argument from the success typing arguments: (any(),'parity')
test/support/test_helper.ex:68: Function do_deposit/3 has no local return
apps/omg/lib/omg/utxo/position.ex:46: Type specification 'Elixir.OMG.Utxo.Position':'decode!'(number()) -> t() is a supertype of the success typing: 'Elixir.OMG.Utxo.Position':'decode!'(number()) -> {'utxo_position',non_neg_integer(),non_neg_integer(),char()}
apps/omg/lib/omg/utxo/position.ex:52: Type specification 'Elixir.OMG.Utxo.Position':decode(number()) -> {'ok',t()} | {'error','encoded_utxo_position_too_low'} is a supertype of the success typing: 'Elixir.OMG.Utxo.Position':decode(number()) -> {'error','encoded_utxo_position_too_low'} | {'ok',{'utxo_position',non_neg_integer(),non_neg_integer(),char()}}
apps/omg/lib/omg/utxo/position.ex:76: Type specification 'Elixir.OMG.Utxo.Position':get_position(pos_integer()) -> {non_neg_integer(),non_neg_integer(),non_neg_integer()} is a supertype of the success typing: 'Elixir.OMG.Utxo.Position':get_position(pos_integer()) -> {non_neg_integer(),non_neg_integer(),char()}
apps/omg_child_chain_rpc/lib/omg_child_chain_rpc/web/endpoint.ex:15: Expression produces a value of type 'error' | 'excluded' | 'ignored' | 'unsampled' | {'ok',binary() | pid() | #{'__struct__':='Elixir.Task', 'owner':='nil' | pid(), 'pid':='nil' | pid(), 'ref':='nil' | reference()}}, but this value is unmatched
apps/omg_watcher_rpc/lib/web/endpoint.ex:15: Expression produces a value of type 'error' | 'excluded' | 'ignored' | 'unsampled' | {'ok',binary() | pid() | #{'__struct__':='Elixir.Task', 'owner':='nil' | pid(), 'pid':='nil' | pid(), 'ref':='nil' | reference()}}, but this value is unmatched
lib/phoenix/router.ex:316: The pattern 'error' can never match the type {#{'conn':='nil', 'log':='debug', 'path_params':=map(), 'pipe_through':=[any(),...], 'plug':='Elixir.OMG.ChildChainRPC.Web.Controller.Block' | 'Elixir.OMG.ChildChainRPC.Web.Controller.Fallback' | 'Elixir.OMG.ChildChainRPC.Web.Controller.Transaction', 'plug_opts':='Elixir.Route.NotFound' | 'get_block' | 'submit', 'route':=<<_:48,_:_*8>>},fun((_,map()) -> any()),fun((_) -> map()),{'Elixir.OMG.ChildChainRPC.Web.Controller.Block','get_block'} | {'Elixir.OMG.ChildChainRPC.Web.Controller.Fallback','Elixir.Route.NotFound'} | {'Elixir.OMG.ChildChainRPC.Web.Controller.Transaction','submit'}}
lib/phoenix/router.ex:316: The pattern 'error' can never match the type {#{'conn':='nil', 'log':='debug', 'path_params':=map(), 'pipe_through':=[any(),...], 'plug':='Elixir.OMG.WatcherRPC.Web.Controller.Account' | 'Elixir.OMG.WatcherRPC.Web.Controller.Alarm' | 'Elixir.OMG.WatcherRPC.Web.Controller.Challenge' | 'Elixir.OMG.WatcherRPC.Web.Controller.Fallback' | 'Elixir.OMG.WatcherRPC.Web.Controller.InFlightExit' | 'Elixir.OMG.WatcherRPC.Web.Controller.Status' | 'Elixir.OMG.WatcherRPC.Web.Controller.Transaction' | 'Elixir.OMG.WatcherRPC.Web.Controller.Utxo', 'plug_opts':=atom(), 'route':=<<_:48,_:_*8>>},fun((_,map()) -> any()),fun((_) -> map()),{'Elixir.OMG.WatcherRPC.Web.Controller.Account' | 'Elixir.OMG.WatcherRPC.Web.Controller.Alarm' | 'Elixir.OMG.WatcherRPC.Web.Controller.Challenge' | 'Elixir.OMG.WatcherRPC.Web.Controller.Fallback' | 'Elixir.OMG.WatcherRPC.Web.Controller.InFlightExit' | 'Elixir.OMG.WatcherRPC.Web.Controller.Status' | 'Elixir.OMG.WatcherRPC.Web.Controller.Transaction' | 'Elixir.OMG.WatcherRPC.Web.Controller.Utxo',atom()}}

####
#
# Protocol-related problems, these ignores workaround the problem reported
# here: https://github.com/elixir-lang/elixir/issues/7708 and here https://github.com/jeremyjh/dialyxir/issues/221
# fixed in https://github.com/jeremyjh/dialyxir/commit/3d0a13f17a46649bca2413d57cef45bb278d1474, not yet released in `dialyxir`
# undo once we use the `dialyxir` release that includes this (presumably >1.0.0-rc.6)
:0: Unknown function 'Elixir.OMG.State.Transaction.Protocol.Atom':'__impl__'/1
:0: Unknown function 'Elixir.OMG.State.Transaction.Protocol.BitString':'__impl__'/1
:0: Unknown function 'Elixir.OMG.State.Transaction.Protocol.Float':'__impl__'/1
:0: Unknown function 'Elixir.OMG.State.Transaction.Protocol.Function':'__impl__'/1
:0: Unknown function 'Elixir.OMG.State.Transaction.Protocol.Integer':'__impl__'/1
:0: Unknown function 'Elixir.OMG.State.Transaction.Protocol.List':'__impl__'/1
:0: Unknown function 'Elixir.OMG.State.Transaction.Protocol.Map':'__impl__'/1
:0: Unknown function 'Elixir.OMG.State.Transaction.Protocol.PID':'__impl__'/1
:0: Unknown function 'Elixir.OMG.State.Transaction.Protocol.Port':'__impl__'/1
:0: Unknown function 'Elixir.OMG.State.Transaction.Protocol.Reference':'__impl__'/1
:0: Unknown function 'Elixir.OMG.State.Transaction.Protocol.Tuple':'__impl__'/1
:0: Unknown function 'Elixir.OMG.Output.Atom':'__impl__'/1
:0: Unknown function 'Elixir.OMG.Output.BitString':'__impl__'/1
:0: Unknown function 'Elixir.OMG.Output.Float':'__impl__'/1
:0: Unknown function 'Elixir.OMG.Output.Function':'__impl__'/1
:0: Unknown function 'Elixir.OMG.Output.Integer':'__impl__'/1
:0: Unknown function 'Elixir.OMG.Output.List':'__impl__'/1
:0: Unknown function 'Elixir.OMG.Output.Map':'__impl__'/1
:0: Unknown function 'Elixir.OMG.Output.PID':'__impl__'/1
:0: Unknown function 'Elixir.OMG.Output.Port':'__impl__'/1
:0: Unknown function 'Elixir.OMG.Output.Reference':'__impl__'/1
:0: Unknown function 'Elixir.OMG.Output.Tuple':'__impl__'/1
:0: Unknown function 'Elixir.OMG.Output.Protocol.Atom':'__impl__'/1
:0: Unknown function 'Elixir.OMG.Output.Protocol.BitString':'__impl__'/1
:0: Unknown function 'Elixir.OMG.Output.Protocol.Float':'__impl__'/1
:0: Unknown function 'Elixir.OMG.Output.Protocol.Function':'__impl__'/1
:0: Unknown function 'Elixir.OMG.Output.Protocol.Integer':'__impl__'/1
:0: Unknown function 'Elixir.OMG.Output.Protocol.List':'__impl__'/1
:0: Unknown function 'Elixir.OMG.Output.Protocol.Map':'__impl__'/1
:0: Unknown function 'Elixir.OMG.Output.Protocol.PID':'__impl__'/1
:0: Unknown function 'Elixir.OMG.Output.Protocol.Port':'__impl__'/1
:0: Unknown function 'Elixir.OMG.Output.Protocol.Reference':'__impl__'/1
:0: Unknown function 'Elixir.OMG.Output.Protocol.Tuple':'__impl__'/1
#
####
